version: '2'

services:
  application:
    image: 'university:latest'
    build:
      context: .
    container_name: application
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/university
      - SPRING_DATASOURCE_USERNAME=docker-postgres
      - SPRING_DATASOURCE_PASSWORD=docker-postgres

  db:
    image: 'postgres:15.1'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=docker-postgres
      - POSTGRES_PASSWORD=docker-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./src/main/resources/1.schema.sql:/docker-entrypoint-initdb.d/1.schema.sql
      - ./src/main/resources/2.data.sql:/docker-entrypoint-initdb.d/2.data.sql
volumes:
  dbdata:
